import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';

// ─── Load & pre-process the Figma export ────────────────────────────────────
// Figma's multi-mode tokens export as { $value: { Light: ..., Dark: ... } }
// SD expects a flat $value per token — we split into three separate token trees:
//   1. brand   (single-mode primitives)
//   2. alias   (single-mode semantic aliases)
//   3. light   (Mapped layer, Light mode values only)
//   4. dark    (Mapped layer, Dark mode values only)

const raw = JSON.parse(readFileSync('./lamplight-design-tokens.json', 'utf8'));

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Resolve a Figma alias ref like "{Brand.Scale.100}" to a CSS var reference */
function figmaRefToCssVar(ref) {
  // "{Brand.Scale.100}" -> "var(--brand-scale-100)"
  const inner = ref.replace(/^\{|\}$/g, '');
  const slug = inner
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/\./g, '-');
  return `var(--${slug})`;
}

function isRef(v) {
  return typeof v === 'string' && v.startsWith('{') && v.endsWith('}');
}

/** Flatten a nested token object into SD-compatible shape, selecting a mode for multi-mode tokens */
function flattenTokens(obj, mode = null, prefix = '') {
  const out = {};

  function walk(node, path) {
    // Skip Figma metadata keys
    if (path[path.length - 1]?.startsWith('$')) return;

    if (node.$type !== undefined) {
      // Leaf token
      let value = node.$value;

      // Handle multi-mode values (Mapped layer)
      if (mode && typeof value === 'object' && !Array.isArray(value) && value[mode] !== undefined) {
        value = value[mode];
      }

      // Skip tokens with empty-string values (Scale/0 edge case in old export)
      if (value === '' || value === null || value === undefined) {
        // Default Scale/0 to 0
        if (path.at(-1) === '0' && path.includes('Scale')) {
          value = 0;
        } else {
          return;
        }
      }

      // Skip tokens that still have multi-mode values when no mode selected
      if (typeof value === 'object' && !Array.isArray(value) && !isRef(value)) {
        return; // responsive tokens with Desktop/Mobile/Tablet — handled separately
      }

      // Prefix with the collection name so emitted var names match alias references
      // e.g. Brand tree → "brand.slate.100", Alias tree → "alias.primary.600"
      const key = (prefix ? prefix + '.' : '') + path.join('.');
      out[key] = { $value: value, $type: node.$type };
      if (node.$description) out[key].$description = node.$description;
      return;
    }

    for (const [k, v] of Object.entries(node)) {
      if (k.startsWith('$')) continue;
      if (typeof v === 'object' && !Array.isArray(v)) {
        walk(v, [...path, k]);
      }
    }
  }

  walk(obj, []);
  return out;
}

/** Convert a flat dot-path key to a kebab-case CSS var name */
function toVar(key) {
  return '--' + key
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/\./g, '-');
}

/** Resolve Figma alias refs to CSS var() references */
function resolveValue(value) {
  if (isRef(value)) return figmaRefToCssVar(value);
  if (typeof value === 'number') return value + 'px';
  return value;
}

// ─── Build separate token trees ──────────────────────────────────────────────

const brandTokens   = flattenTokens(raw.Brand, null, 'brand');
const aliasTokens   = flattenTokens(raw.Alias, null, 'alias');
const lightTokens   = flattenTokens(raw.Mapped, 'Light');
const darkTokens    = flattenTokens(raw.Mapped, 'Dark');

// ─── Emit CSS files ──────────────────────────────────────────────────────────

function emitCss(tokens, selector, comment) {
  const lines = [`/* ${comment} — generated by sd.config.js, do not edit */`, `${selector} {`];
  for (const [key, token] of Object.entries(tokens)) {
    const cssVar = toVar(key);
    const val = resolveValue(token.$value);
    const desc = token.$description ? ` /* ${token.$description} */` : '';
    lines.push(`  ${cssVar}: ${val};${desc}`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

mkdirSync('./css', { recursive: true });

// 1. Brand primitives — :root, always loaded
writeFileSync('./css/brand.css', emitCss(brandTokens, ':root', 'Brand primitives'));

// 2. Alias tokens — :root, always loaded
writeFileSync('./css/alias.css', emitCss(aliasTokens, ':root', 'Alias tokens'));

// 3. Light mapped layer — default (light) mode
writeFileSync('./css/mapped.light.css', emitCss(lightTokens, ':root, [data-theme="light"]', 'Mapped tokens — Light mode'));

// 4. Dark mapped layer — dark mode override
writeFileSync('./css/mapped.dark.css', emitCss(darkTokens, '[data-theme="dark"]', 'Mapped tokens — Dark mode'));

// 5. Responsive typography — CSS custom media + per-breakpoint vars
const responsiveLines = [
  '/* Responsive typography — generated by sd.config.js, do not edit */',
  '',
  '/* Desktop-first: base = Desktop values */',
  ':root {',
];
const headings = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];
const paras = ['paragraph xsm', 'paragraph sm', 'paragraph md', 'paragraph lg'];
const allScales = [...headings, ...paras];

for (const scale of allScales) {
  const node = raw.Responsive[scale];
  if (!node) continue;
  const slug = scale.replace(/\s+/g, '-');
  const fs = node['font size']?.['$value'];
  const lh = node['line height']?.['$value'];
  if (fs?.Desktop !== undefined) {
    responsiveLines.push(`  --type-${slug}-size: ${fs.Desktop}px;`);
    responsiveLines.push(`  --type-${slug}-lh: ${lh.Desktop}px;`);
  }
}
responsiveLines.push('}', '');

// Tablet overrides
responsiveLines.push('@media (max-width: 1024px) {', '  :root {');
for (const scale of allScales) {
  const node = raw.Responsive[scale];
  if (!node) continue;
  const slug = scale.replace(/\s+/g, '-');
  const fs = node['font size']?.['$value'];
  const lh = node['line height']?.['$value'];
  if (fs?.Tablet !== undefined) {
    responsiveLines.push(`    --type-${slug}-size: ${fs.Tablet}px;`);
    responsiveLines.push(`    --type-${slug}-lh: ${lh.Tablet}px;`);
  }
}
responsiveLines.push('  }', '}', '');

// Mobile overrides
responsiveLines.push('@media (max-width: 640px) {', '  :root {');
for (const scale of allScales) {
  const node = raw.Responsive[scale];
  if (!node) continue;
  const slug = scale.replace(/\s+/g, '-');
  const fs = node['font size']?.['$value'];
  const lh = node['line height']?.['$value'];
  if (fs?.Mobile !== undefined) {
    responsiveLines.push(`    --type-${slug}-size: ${fs.Mobile}px;`);
    responsiveLines.push(`    --type-${slug}-lh: ${lh.Mobile}px;`);
  }
}
responsiveLines.push('  }', '}', '');

writeFileSync('./css/responsive.css', responsiveLines.join('\n'));

// 6. Tailwind v4 @theme block — maps CSS vars into Tailwind's design token system
// Tailwind v4 reads @theme { --color-*: ...; } and generates utilities automatically
const twLines = [
  '/* Tailwind v4 @theme — generated by sd.config.js, do not edit */',
  '/* Import this file in your globals.css AFTER the other token CSS files */',
  '',
  '@theme {',
  '  /* ── Colours: mapped semantic layer (light/dark via CSS vars) ── */',
];

// Map Mapped tokens into Tailwind color namespace
const mappedGroups = { Text: 'text', Icons: 'icon', Surface: 'surface', Border: 'border' };
for (const [group, prefix] of Object.entries(mappedGroups)) {
  for (const key of Object.keys(lightTokens).filter(k => k.startsWith(group + '.'))) {
    const subkey = key.slice(group.length + 1).replace(/\./g, '-');
    const cssVar = toVar(key);
    twLines.push(`  --color-${prefix}-${subkey}: var(${cssVar});`);
  }
}

twLines.push('', '  /* ── Spacing ── */');
const spacingMap = { xs: 1, sm: 2, md: 3, lg: 4, xl: 6, '2xl': 8, '3xl': 12 };
for (const [name] of Object.entries(spacingMap)) {
  twLines.push(`  --spacing-${name}: var(--alias-spacing-${name});`);
}

twLines.push('', '  /* ── Border radius ── */');
for (const r of ['sm', 'md', 'lg', 'xl', 'full']) {
  twLines.push(`  --border-radius-${r}: var(--alias-border-radius-${r});`);
  twLines.push(`  --radius-${r}: var(--alias-border-radius-${r});`);
}

twLines.push('', '  /* ── Focus ring ── */');
twLines.push('  --focus-ring-width: var(--alias-focus-ring-width);');
twLines.push('  --focus-ring-offset: var(--alias-focus-ring-offset);');

twLines.push('', '  /* ── Typography ── */');
twLines.push('  --font-heading: var(--brand-font-family-headings);');
twLines.push('  --font-body: var(--brand-font-family-body);');
twLines.push('  --font-mono: var(--brand-font-family-mono);');

twLines.push('', '  /* ── Z-index ── */');
for (const z of ['base', 'dropdown', 'sticky', 'overlay', 'modal', 'popover', 'toast']) {
  twLines.push(`  --z-${z}: var(--brand-z-index-${z});`);
}

twLines.push('}', '');
writeFileSync('./css/tailwind-theme.css', twLines.join('\n'));

// ─── Summary ─────────────────────────────────────────────────────────────────
console.log('✅ Style Dictionary build complete');
console.log(`   brand.css         — ${Object.keys(brandTokens).length} tokens`);
console.log(`   alias.css         — ${Object.keys(aliasTokens).length} tokens`);
console.log(`   mapped.light.css  — ${Object.keys(lightTokens).length} tokens`);
console.log(`   mapped.dark.css   — ${Object.keys(darkTokens).length} tokens`);
console.log(`   responsive.css    — ${allScales.length} type scales × 3 breakpoints`);
console.log(`   tailwind-theme.css — @theme block`);
